name: Bug report
description: Create a report to help us improve
title: "[Bug report]"
labels: ["bug"]
projects: ["Add project"]
assignees: jwass
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Outline bug
      description: Outline Outline bug Details
      placeholder: Tell us what you see
      value: "Add details" 
    validations:
      required: true
  - type: dropdown
    id: TF-Groups
    attributes:
      label: Issue dependency with other TF Groups
      multiple: true
      options:
        - No Dependency
        - Admin
        - Address
        - Base
        - Data Platform
        - Dev Advocacy
        - GERs
        - Schema
        - Transportation
